### ISSUE TITLE
Eror saat diintsall di SLiMS 9.6.1

### ISSUE THREAD

**Issue by wiliamraharjo** [drajathasan/visitorwebcounter#1]
Plugin visitor web counter saya coba di SLiMS 9.6.1 eror pada tampilan saat akses OPAC muncul dialog box seoerti berikut

![eror-di-opac](https://github.com/drajathasan/visitorwebcounter/assets/47516879/267f6f30-6417-4a31-a4e4-4b683d7d07b1)

Pada database nya masuk data seperti berikut 

![eror-di-database](https://github.com/drajathasan/visitorwebcounter/assets/47516879/62d182f9-9f81-4746-909d-84d42c34ed72)

Server yang saya gunakan :
10.5.24-MariaDB-cll-lve - MariaDB Server
PHP 8.2 

Pada footer OPAC tidak tampil statistik  visitorwebcounter nya 

![eror-di-opac-footer](https://github.com/drajathasan/visitorwebcounter/assets/47516879/06f6cb8e-e622-4159-b131-fee65915b8f2)

Terima kasih atas bantuan nya 😁

**Comment by drajathasan** [comment]
> Plugin visitor web counter saya coba di SLiMS 9.6.1 eror pada tampilan saat akses OPAC muncul dialog box seoerti berikut
> 
> ![eror-di-opac](https://private-user-images.githubusercontent.com/47516879/332263271-267f6f30-6417-4a31-a4e4-4b683d7d07b1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNjIyMzMsIm5iZiI6MTcxNjI2MTkzMywicGF0aCI6Ii80NzUxNjg3OS8zMzIyNjMyNzEtMjY3ZjZmMzAtNjQxNy00YTMxLWE0ZTQtNGI2ODNkN2QwN2IxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAzMjUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOGRjZjNlMmVhMGYyYjUxNTI2YjliOWY3ZTM3OWUxODhmYWNjN2EyNzdlZjk5YzQ0OGNkZDg5NWRkYzAyZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q1UxFZ4u2Hqdqfe5VtE33eM2nvzqz66oXVksdhZ_H2U)
> 
> Pada database nya masuk data seperti berikut
> 
> ![eror-di-database](https://private-user-images.githubusercontent.com/47516879/332263545-62d182f9-9f81-4746-909d-84d42c34ed72.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNjIyMzMsIm5iZiI6MTcxNjI2MTkzMywicGF0aCI6Ii80NzUxNjg3OS8zMzIyNjM1NDUtNjJkMTgyZjktOWY4MS00NzQ2LTkwOWQtODRkNDJjMzRlZDcyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAzMjUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwN2ZlOWFiNzMxYWYyNmYwYmM1YmEwYmU1NjI0ZTUxZjY0MDk0YjdlZTFhMzdmZDdkMGRkNGYwYTBmYzI3NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zFa3ZKZJ8a67tljMFJ0nOq8KagEf82GSycgsAiP9uvE)
> 
> Server yang saya gunakan : 10.5.24-MariaDB-cll-lve - MariaDB Server PHP 8.2
> 
> Pada footer OPAC tidak tampil statistik visitorwebcounter nya
> 
> ![eror-di-opac-footer](https://private-user-images.githubusercontent.com/47516879/332263938-06f6cb8e-e622-4159-b131-fee65915b8f2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNjIyMzMsIm5iZiI6MTcxNjI2MTkzMywicGF0aCI6Ii80NzUxNjg3OS8zMzIyNjM5MzgtMDZmNmNiOGUtZTYyMi00MTU5LWIxMzEtZmVlNjU5MTViOGYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAzMjUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzODIyMTM5OThiNjk1YjE3NzdlOGEzZjA3OGI4YzE4MmJkNTJhYTE2MzQzNzlhNjQ5OGQwNzI1ZjFiYWJmZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nZ_4u6cobbYP6XMHcxWy4PILnpkHFrQ8TErdAzwOoiM)
> 
> Terima kasih atas bantuan nya 😁

Itu terjadi karena versi PHP nya yaitu 8.2. Plugin tersebut seingat saya dibuat dengan PHP 7.4. Maka untuk mengetahui error nya, 
1. Pada tab SLiMS di browser tekan F12, 
2. Cari tab network
3. cari kata Fetch/XHR lalu klik.
4. Reload halaman opac nya kembali
5. Lihat request yang mengarah ke path visitor
6. klik, nanti akan muncul informasi detail nya, klik kata respon
7. Maka akan muncul detail error nya
8. Jika pada poin 7 tidak muncul, ubah environment dari production ke development (lihat video ini https://youtu.be/1J3vQYftORw?t=59&si=6ZYCfzLuwvrKVBOx) untuk merubah environment SLiMS. Lalulkan ulang langkah ke 4.
9. Maka anda akan mendapatkan detail error kenapa fitur itu tidak bekerja.
